### ISSUE TITLE
Getting error while integrating .aar file 

### ISSUE THREAD

**Issue by gunwantsonawane** [LP-Messaging/Android-Messaging-SDK#2]
Error :- 
/Users/gunwant/test/AndroidManifest.xml:9:18-45 Error:
	Attribute application@allowBackup value=(false) from [com.test.mobile:safe-browsing-android:3.0.15-SNAPSHOT:release] AndroidManifest.xml:9:18-45
	is also present at [:lp_messaging:] AndroidManifest.xml:11:18-44 value=(true).
	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:98:5-302:19 to override.

Solution :- 
android:allowBackup should not be used in library
https://github.com/chrisbanes/PhotoView/issues/199

**Comment by ofirant** [comment]
Fixed in v1.2.2
