### ISSUE TITLE
76 warnings - How to fix them?

### ISSUE THREAD

**Issue by refnandor** [LP-Messaging/Android-Messaging-SDK#41]
Hi, Anyone knows how to avoid the following warnings (SDK V2.8)? We have a bank as a customer so they are requesting to provide a solution or alternative to fix those warnings. Thanks 

Please rename the script.css for .js

[Warnings SDK Live Person.docx](https://github.com/LP-Messaging/Android-Messaging-SDK/files/1497210/Warnings.SDK.Live.Person.docx)
[Warnings LP 2.8.zip](https://github.com/LP-Messaging/Android-Messaging-SDK/files/1497213/Warnings.LP.2.8.zip)

**Comment by dvillacis94** [comment]
As you know Linters differ depending on versions, and can throw different results.
Is this crashing the App? or causing compilation issues?

**Comment by refnandor** [comment]
Hi David. 

The app is not crashing, or having compilation issues but the "Integrations" department is asking to remove them if it is possible, so far they haven't sent any justification or security threat about this, so we are waiting for their response after LP says that cannot be erased.

**Comment by refnandor** [comment]
Since the liveperson point of view, any of them can be vulnerabilities?

**Comment by refnandor** [comment]
Hi. 

There is a new warning analysis on Bancomer side, attached please find the updated one (those warning appears on the Android Studio):
![image](https://user-images.githubusercontent.com/32464396/40439545-d81297be-5e80-11e8-8ec6-f1fcf4797b66.png)
The project settings above.

[Warnigs sdk Live Person.zip](https://github.com/LP-Messaging/Android-Messaging-SDK/files/2032055/Warnigs.sdk.Live.Person.zip)

NOTE: **Please change the .css extension for .js **


Please help us to provide a solution for them or an alternative to avoid that. In addition please let us know if some of the warnings can be treated as a security vulnerabilities.

Thanks
