### ISSUE TITLE
Push Notification issues - account 85316665

### ISSUE THREAD

**Issue by refnandor** [LP-Messaging/Android-Messaging-SDK#43]
Push notification on iOS are not working, this is what we have on the account:

1.- AppDelegate:

![image](https://user-images.githubusercontent.com/32464396/34004903-dfdcd15c-e0be-11e7-8802-36643726c6fb.png)

![image](https://user-images.githubusercontent.com/32464396/34004933-fad1eccc-e0be-11e7-96d8-62f43bcec2dd.png)

2.- Push notifications:

![image](https://user-images.githubusercontent.com/32464396/34004954-0df5b27a-e0bf-11e7-901e-4a3b4d466132.png)

3.- Enable the application 
![image](https://user-images.githubusercontent.com/32464396/34004968-19591ca6-e0bf-11e7-9aa0-9c255918f0a9.png)

4.- Subir los certificados del desarrollador a la consola deLive Person, así como incluir la cadena "-DEV" al mobile app name:
![image](https://user-images.githubusercontent.com/32464396/34004986-2662d2de-e0bf-11e7-8629-5e12f2ffc5d9.png)

SDK V2.7

**Comment by dvillacis94** [comment]
Hi,

Which version of the SDK, iOS and Xcode are you using?

**Comment by refnandor** [comment]
Hi David. 

We will re test using new certificates and the SDK V2.9.4, Bancomer will send me their resultus on Monday 15th. Thanks for the follow up.
Regards
