### ISSUE TITLE
In '3.1.0' NotificationHandler doesn't call setContentIntent()

### ISSUE THREAD

**Issue by parrishsteve** [LP-Messaging/Android-Messaging-SDK#59]
The source for NotificationHandler.java in 3.1.0 doesn't call setContentIntent(), consequently with no PendingIntent assigned to the notification, then the notifications will not launch an app when they are clicked by users. 

I would think this is a critical issue.  Anyone using 3.1.0 will have notifications that will do nothing.

I'm not sure what version this bug was introduced, I was using 2.9.2 which worked fine but 3.1.0 is busted.

**Comment by parrishsteve** [comment]
Bug was probably introduced when LP added support for API 26 notifications.

**Comment by dvillacis94** [comment]
Hi @parrishsteve,

From 3.1 onwards the SDK Default notification is only for display purposes, if you want to add that behavior you'll need to implement your on Notification Builder, this is expected and is not a bug, also consider that you will need to handle for both Non-Oreo and Oreo devices.

**Comment by parrishsteve** [comment]
Roger that!  Thank you sir.
